### ISSUE TITLE
Apply for GitHub UCL organization group

### ISSUE THREAD

**Issue by raquelalegre** [UCL/Holder#22]
Talk to James RSD and find out what to do.

**Comment by jenshnielsen** [comment]
https://www.ucl.ac.uk/isd/services/research-it/research-software/infrastructure/github/signup

**Comment by raquelalegre** [comment]
Thanks @jenshnielsen !

**Comment by raquelalegre** [comment]
I've created [this new organisation](https://github.com/EIT-team) and sent invites to all but Mayo, since I don't have her GitHub ID yet. 

I'm applying for you to get some free private repos, but not sure what to reply to this question in the application form:

`How is your research funded?`

The suggested reply is `UK and European Research Councils`, but not sure if that's applicable, or if I have to mention Black Rock or other funders you have. Can someone help, please? :)

**Comment by Jimbles** [comment]
Hi Raquel,

The only person that this may not be applicable for is Mayo with Blackrock, but as they havent shelled out any money yet I dont think it matters yet! I think its safe to choose that.

**Comment by raquelalegre** [comment]
OK, it's done :)  

```
Hey Raquel Alegre, we have awesome news...

We've upgraded @EIT-team to a Silver plan with free private repositories. If you need help getting started with Git and GitHub, check out:

https://help.github.com/articles/what-are-other-good-resources-for-learning-git-and-github


Spread the word: we love giving educational discounts to students, teachers, administrators, and researchers! Please send them to https://education.github.com

Have an Octotastic day!

- The GitHub Education Team

```
